site_name: TimeCave
site_url: http://timecave.com

theme:
  name: material
  language: en
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.integrate
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: teal
      accent: purple
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: teal
      accent: lime

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/miguel-santos-loureiro/
      name: Miguel Loureiro's LinkedIn page
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/beatriz-pereira-lourenço/
      name: Beatriz Lourenço's LinkedIn page

nav:
  - Home: index.md
  - Getting Started: starters.md
  - API reference:
    - Overview: API_ref/index.md
    - Data characteristics:
      - Overview: API_ref/data_characteristics/index.md
      - get_features: API_ref/data_characteristics/get_features.md
      - strength_of_trend: API_ref/data_characteristics/sot.md
      - mean_crossing_rate: API_ref/data_characteristics/mean_cr.md
      - median_crossing_rate: API_ref/data_characteristics/med_cr.md
    - Metrics: 
      - Overview: API_ref/metrics/index.md
      - PAE: API_ref/metrics/pae.md
      - APAE: API_ref/metrics/apae.md
      - RPAE: API_ref/metrics/rpae.md
      - RAPAE: API_ref/metrics/rapae.md
      - MC_metric: API_ref/metrics/MC_metric.md
      - under_over_estimation: API_ref/metrics/under_over.md
    - Utilities:
      - Overview: API_ref/utils/index.md
      - Nyquist_min_samples: API_ref/utils/nyquist.md
      - heuristic_min_samples: API_ref/utils/heuristic.md
      - true_test_indices: API_ref/utils/indices.md
    - Validation methods:
      - Overview: API_ref/validation_methods/index.md
  - About: about.md

not_in_nav: |
  /data_characteristics.md
  /metrics.md
  /utils.md

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: numpy
            show_submodules: true